spring.application.name=movie-service
server.port=${PORT:8081}

# Database Configuration (MongoDB)
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/cineverse}
spring.data.mongodb.auto-index-creation=true
de.flapdoodle.mongodb.embedded.version=6.0.11

# JWT Configurations
cineverse.jwt.secret=${JWT_SECRET:9a6747fc6259aa374abfcd182e1858c290a618fce1868a8677c7f3df4ab1e483}
cineverse.jwt.expiration-ms=86400000
