spring.application.name=CineVerse
server.port=${PORT:8080}

# Database Configuration (PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://127.0.0.1:5432/cineverse}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Configurations
# Secret is a 256-bit Hex encoded key
cineverse.jwt.secret=${JWT_SECRET:9a6747fc6259aa374abfcd182e1858c290a618fce1868a8677c7f3df4ab1e483}
cineverse.jwt.expiration-ms=86400000
